### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by leandrosimoes**
Now it works on windows platform too.

### CODE REVIEW

**Comment by wswebcreation** [comment]
Awesome, thanks, will check it when I get home and release a new version

**Comment by leandrosimoes** [comment]
Thanks @wswebcreation !

**Comment by wswebcreation** [comment]
Thanks for fixing this!

season-11-the-simpsons-11x5-3orifhF0g6TPRgs3G8

**Comment by leandrosimoes** [comment]
🤣 You're welcome!

**Pull request merged**
